# Generated by Django 5.2.7 on 2025-11-20 20:38

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0079_alter_characterreference_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='advertising_agency_address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='advertising_agency_authorized_rep',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='advertising_agency_designation',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='advertising_agency_email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='advertising_agency_telephone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='sponsor_address',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='sponsor_authorized_rep',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='sponsor_designation',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='sponsor_email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True),
        ),
        migrations.AlterField(
            model_name='salespromotionpermitapplication',
            name='sponsor_telephone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
